"""contract registry and audit history

Revision ID: c8d789679fac
Revises: 
Create Date: 2026-08-19 17:55:37.636276

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c8d789679fac"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_event",
        sa.Column(
            "seq",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("jti", sa.String(length=64), nullable=True),
        sa.Column("order_id", sa.String(length=64), nullable=True),
        sa.Column("consumer_id", sa.String(length=255), nullable=True),
        sa.Column("occurred_at", sa.BigInteger(), nullable=False),
        sa.Column("detail", sa.String(length=1024), nullable=True),
        sa.PrimaryKeyConstraint("seq"),
    )
    with op.batch_alter_table("audit_event", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_event_jti"), ["jti"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_audit_event_order_id"), ["order_id"], unique=False
        )

    op.create_table(
        "contract",
        sa.Column("jti", sa.String(length=64), nullable=False),
        sa.Column("order_id", sa.String(length=64), nullable=False),
        sa.Column("consumer_id", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("iat", sa.BigInteger(), nullable=False),
        sa.Column("exp", sa.BigInteger(), nullable=False),
        sa.Column("registered_at", sa.BigInteger(), nullable=False),
        sa.Column("status_changed_at", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("jti"),
    )
    with op.batch_alter_table("contract", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_contract_order_id"), ["order_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("contract", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_contract_order_id"))

    op.drop_table("contract")
    with op.batch_alter_table("audit_event", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_event_order_id"))
        batch_op.drop_index(batch_op.f("ix_audit_event_jti"))

    op.drop_table("audit_event")
    # ### end Alembic commands ###
